language:
  node_js
node_js:
  - stable
script:
  - npm run build
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: dist
  repo: inlinedb/inlinedb.github.io
  skip_cleanup: true
  target_branch: master
  on:
    branch: master
